version: '3.8'

services:
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=test-usr'
      - 'SPRING_AMQP_DESERIALIZATION_TRUST_ALL'
    ports:
      - 5672:5672