version: '3.8'

networks:
  progress:

volumes:
  postgress:
  rabbit:
  storage:

services:
  db:
    build: ./postgresdb
    container_name: database
    networks:
      - progress
    ports:
      - 5432:5432
    environment:
      - TZ="Asia/Yangon"
    volumes:
      - postgress:/var/lib/postgresql/data

  message:
    build: ./rabbitmq
    container_name: rabbitmq
    networks:
      - progress
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit:/var/lib/rabbitmq
