insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('014', 'YESC', 'Seik Kyee Kha Naung To');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('036', 'YESC', 'Insein');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('046', 'YESC', 'Taik Kyi');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('049', 'YESC', 'Tawantay');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('055', 'YESC', 'Hmawbi');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('056', 'YESC', 'Okkan');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('065', 'YESC', 'Htauk Kyant');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('068', 'YESC', 'Khyan');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('077', 'YESC', 'Hlegu');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('079', 'YESC', 'Kun Chan Kone');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('086', 'YESC', 'Dala');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('087', 'YESC', 'Thongwa');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('088', 'YESC', 'Min Galar Don');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('104', 'YESC', 'Darpein');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('112', 'YESC', 'Htan Topin');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('129', 'YESC', 'Kyauk Tan');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('195', 'YESC', 'Kawt Mhue');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('264', 'YESC', 'Lak Khote Kone');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('285', 'YESC', 'Kyaik Htaw');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('359', 'YESC', 'North Okkala');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('360', 'YESC', 'Mayangone');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('567', 'YESC', 'Mayangone');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('361', 'YESC', 'Kamayut');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('362', 'YESC', 'Hlaing');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('363', 'YESC', 'South Okkala');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('364', 'YESC', 'Thingangyun');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('365', 'YESC', 'Yankin');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('366', 'YESC', 'Kyimyindine');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('367', 'YESC', 'Sanchaung');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('369', 'YESC', 'Lamadaw');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('370', 'YESC', 'Latha');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('371', 'YESC', 'Pabedan');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('372', 'YESC', 'Kyauktada');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('373', 'YESC', 'Bothahtaung');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('374', 'YESC', 'Pazundaung');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('375', 'YESC', 'Bahan');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('376', 'YESC', 'Dagon');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('377', 'YESC', 'Mingalar Taung Nyunt');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('378', 'YESC', 'Tamwae');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('379', 'YESC', 'Thakayta');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('380', 'YESC', 'Daw Pone');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('388', 'YESC', 'Ahlone');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('404', 'YESC', 'West Hlaingtharyar');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('405', 'YESC', 'East Hlaingtharyar');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('406', 'YESC', 'Shwe Pyi Thar');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('432', 'YESC', 'Ahphyauk');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('464', 'YESC', 'North Dagon');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('465', 'YESC', 'South Dagon');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('466', 'YESC', 'South Dagon');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('505', 'YESC', 'Dagon Seik Kan');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('543', 'YESC', 'Tada');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('558', 'YESC', 'Shwe Pauk Kan');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('559', 'YESC', 'Phoung Kyi');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('563', 'YESC', 'Inntaing');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('564', 'YESC', 'Myaung Daga');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('565', 'YESC', 'Shwelinban');
insert into ESC_SERVICE_TOWNSHIP (code, service, township) values ('566', 'YESC', 'Aye Ywar');